CREATE TABLE Persons (
    PersonID INT PRIMARY KEY AUTO_INCREMENT,
    LastName VARCHAR(255),
    FirstName VARCHAR(255),
    City VARCHAR(255)
);



CREATE TABLE IF NOT EXISTS GOVIES_TS (
	Date VARCHAR(10),
    nYears FLOAT,
	Country VARCHAR(50),
	Rate FLOAT
);
